experiment:
  name: "qlearning_sdn_routing"
  description: "SDN routing optimization using Q-learning"
  duration: 3600
  random_seed: 42

network:
  topology: "linear"
  num_switches: 4
  num_hosts: 8
  link_bandwidth: "10Mbps"

qlearning:
  learning_rate: 0.1
  discount_factor: 0.9
  exploration_rate: 0.1
  state_size: 10
  action_size: 4

traffic:
  pattern: "poisson"
  mean_rate: "100pps"
  packet_size: 1024