network:
  topology_type: "linear"
  switches:
    - s1
    - s2
    - s3
    - s4
  hosts:
    - h1
    - h2
    - h3
    - h4
    - h5
    - h6
    - h7
    - h8
  links:
    - [s1, s2, 1, 1]
    - [s2, s3, 2, 1]
    - [s3, s4, 2, 1]
    - [s1, h1, 3, 1]
    - [s1, h2, 4, 1]
    - [s2, h3, 3, 1]
    - [s2, h4, 4, 1]
    - [s3, h5, 3, 1]
    - [s3, h6, 4, 1]
    - [s4, h7, 2, 1]
    - [s4, h8, 3, 1]